version: "3.8"

services:
  app:
    container_name: space-x-fs-client
    image: space-x-fs-client
    build:
      context: .
      target: development
    volumes:
      - ./src:/app/src
    ports:
      - 3001:3001
