version: "3.8"

services:
  app:
    container_name: space-x-fs-server
    image: space-x-fs-server
    build:
      context: .
      target: development
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000
